### ISSUE TITLE
batrips$duration is seconds not minutes

### ISSUE THREAD

**Issue by mattdowle** [arunsrinivasan/bikeshare14#1]
``` R
> trips[1, end_date-start_date]
Time difference of 7 mins
> trips[1, duration]
[1] 435
```

`?batrips` says 'minutes' but should be 'seconds'

**Comment by arunsrinivasan** [comment]
Noticed it after pushing to CRAN. Fixed here: https://github.com/arunsrinivasan/bikeshare14/commit/694f9067fd6788f67ccf4f61786a15fe3ce527a6
